models/ingredient.py
from models import db

class Ingredient(db.Model):
    __tablename__ = 'ingredient'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    amount = db.Column(db.Integer())
    unit = db.Column(db.String(5))
    recipe_id = db.Column(db.Integer(), db.ForeignKey('recipe.id', ondelete="CASCADE"), nullable=True)
    #plan_id = db.Column(db.Integer(), db.ForeignKey('plan.id', ondelete="CASCADE"), nullable=True)

    unitsWeight = {'g':1, 'hg':100, 'kg':1000} #Valid weight units
    unitsVolume = {'krm':1, 'tsk':5, 'msk':15, 'ml':1, 'cl':10, 'dl':100, 'l':1000} #Valid volume units
    unitsDistinct = {'st':1, 'port':1, 'paket':1} #Valid distinct units

routes/routes.py
from flask import request, Blueprint, render_template, url_for, redirect, session, flash
from sqlalchemy import func
from services.recipe_service import *
from services.ingredient_service import *
from services.user_service import *
from services.plan_service import *


routes = Blueprint('routes', __name__)  # Create a Blueprint

@routes.before_request
def track_history():
    if 'history' not in session:
        session['history'] = []

    # Only track GET requests, to avoid form posts messing it up
    if request.method == 'GET' and request.endpoint not in ('static',):
        current_url = request.path  # only the path, not full URL
        history = session['history']

        # Don't duplicate if refreshing the page
        if not history or history[-1] != current_url:
            history.append(current_url)

        # Keep the history from getting too big (optional)
        if len(history) > 10:
            history.pop(0)

    session.modified = True  # Ensure changes are saved

@routes.context_processor
def inject_back_url():
    history = session.get('history', [])
    if len(history) >= 2:
        back_url = history[-2]
    else:
        back_url = url_for('routes.index')
    return dict(back_url=back_url)

@routes.route('/back', endpoint='go_back')
def go_back():
    history = session.get('history', [])

    if len(history) >= 2:
        history.pop()  # Remove current page from history
        history.pop()
        back_url = history[-1]  # Go to the previous page

        # If the back URL is the same as the current one, then just go to the homepage
        if back_url == request.path:
            return redirect(url_for('routes.index'))

        session['history'] = history
        session.modified = True
        return redirect(back_url)
    else:
        return redirect(url_for('routes.index'))


#Homepage route
@routes.route('/', methods=['POST', 'GET'])
def index():
    if request.method == 'POST':
        value = request.form.get('action')
        if value == 'add':
            username = request.form.get('add_username')
            return create_user(username)
        elif value == 'remove': 
            username = request.form.get('remove_username')
            return remove_user(username)
        elif value == 'edit':
            user_id = request.form.get('user_id')
            new_username = request.form.get('name')
            edit_user(user_id=user_id, new_username=new_username)
        return redirect('/')
    else:
        users = User.query.order_by(func.lower(User.username)).all()
        return render_template('index.html', users=users)

#Recipebank route
@routes.route('/user/<int:user_id>/recipebank', methods=['GET', 'POST'])
def recipebank(user_id):
    if request.method == 'POST':
        value = request.form.get('action')
        if value == "add":
            recipe_name = request.form['name']
            recipe_link = request.form['link']
            recipe_tag = request.form['tag']
            #recipe_tags_string = request.form['tag']
            #recipe_tags = recipe_tags_string.split()
            return add_recipe(user_id, recipe_name, recipe_link, recipe_tag)
        elif value == "remove":
            return remove_recipe(user_id, request.form.get('recipe_id'))
        elif value == "edit":
            recipe_name = request.form['name']
            recipe_link = request.form['link']
            recipe_tag = request.form['tag']
            recipe_id = request.form['recipe_id']
            edit_recipe(recipe_name, recipe_link, recipe_tag, recipe_id)
        return redirect(f'/user/{user_id}/recipebank')

    else:
        user = User.query.get(user_id)  # Find the user by ID
        highlight_id = request.args.get('highlight_id')
        if not user:
            return "User not found", 404  # Handle invalid users

        recipes = Recipe.query.filter_by(user_id=user.id).all()  # Get only this user's recipes
        return render_template('recipebank.html', 
                               highlight_id=highlight_id,
                               recipes=recipes, 
                               user=user)
        
        # recipes = Recipe.query.order_by(Recipe.name).all()
        # return render_template('recipebank.html', recipes=recipes)

#Ingredient for recipe route
@routes.route('/user/<int:user_id>/recipebank/<int:recipe_id>/ingredients', methods=['GET', 'POST'])
def ingredients(user_id, recipe_id):
    if request.method == 'POST':
        value = request.form.get('action')
        if value == "add":
            ingredient_name = request.form['name']
            ingredient_amount = request.form['amount']
            ingredient_unit = request.form['unit']
            if ingredient_name and ingredient_amount and ingredient_unit:
                return add_ingredient(user_id=user_id, recipe_id=recipe_id, ingredient_name=ingredient_name, amount=ingredient_amount, unit=ingredient_unit)
        elif value == "edit":
            edit_name = request.form['name']
            edit_amount = request.form['amount']
            edit_unit = request.form['unit']
            ingredient_id = request.form['ingredient_id']
            edit_ingredient(edit_name, edit_amount, edit_unit, ingredient_id=ingredient_id)
        elif value in Ingredient.unitsWeight.keys() or value in Ingredient.unitsVolume.keys() or value in Ingredient.unitsDistinct.keys():
            return change_unit(user_id, recipe_id=recipe_id, newUnit=value, ingredient_id=request.form.get('ingredient_id'))
        elif value == "remove":
            return remove_ingredient(user_id, recipe_id, request.form.get('ingredient_id'))

        return redirect(f'/user/{user_id}/recipebank/{recipe_id}/ingredients')
    else:
        user = User.query.get(user_id) # Find the user by ID
        recipe = Recipe.query.get(recipe_id) # Find the recipe by ID
        if not recipe:
            return "Recipe not found", 404  # Handle invalid recipe
        if not user:
            return "User not found", 404 # Handle invalid user

        ingredients = Ingredient.query.filter_by(recipe_id=recipe.id).all()  # Get only this user's recipes
        return render_template('ingredients.html', 
                               ingredients=ingredients, 
                               recipe=recipe, 
                               user=user) 
    
#Plans route
@routes.route('/user/<int:user_id>/planbank', methods=['GET', 'POST'])
def plans(user_id):
    if request.method == 'POST':
        value = request.form.get('action')
        if value == "add":
            plan_name = request.form['name']
            return add_plan(user_id, plan_name)
        elif value == "remove":
            return remove_plan(user_id, request.form.get('plan_id'))
        else:
            return redirect(f'/user/{user_id}/planbank')

    else:
        user = User.query.get(user_id) # Find the user by ID
        if not user:
            return "User not found", 404 # Handle invalid user

        plans = Plan.query.filter_by(user_id=user.id).all()  # Get only this user's plans
        return render_template('planbank.html',
                               plans=plans, 
                               user=user) 
    
#Planmaker route
@routes.route('/user/<int:user_id>/planbank/<int:plan_id>/planmaker', methods=['GET', 'POST'])
def planmaker(user_id, plan_id):
    # Get user and plan (with 404 handling)
    user = User.query.get_or_404(user_id)
    plan = Plan.query.get_or_404(plan_id)

    if request.method == 'POST':
        #Initalize passing strings 
        recipe_name = None
        recipe_ingredient = None
        recipe_tag_search = None
        recipe_tag_random = None

        #Initalize search and random lists
        found_recipes = []
        randomized_recipes = []

        #POST Requests
        value = request.form.get('action')
        if value == "search":
            recipe_name = request.form.get('recipe_name', '')
            recipe_ingredient = request.form.get('recipe_ingredient', '')
            recipe_tag_search = request.form.get('tag_search', '')
            found_recipes = find_recipes(user_id, recipe_name, recipe_ingredient, recipe_tag_search) #Returns list of found recipes using search function
            session['prev_value'] = "search"
        elif value == "random":
            recipe_tag_random = request.form.get('tag_random', '')
            randomized_recipes = random_recipes(user_id, recipe_tag_random) #Returns list of randomized recipes using random function
            session['prev_value'] = "random"
        elif value == "add":
            recipe_id = request.form.get('recipe_id')
            add_to_plan(plan, recipe_id)
            if session['prev_value'] == "search":
                found_recipes = find_recipes(user_id, recipe_name, recipe_ingredient, recipe_tag_search) #Returns list of found recipes using search function
            else:
                found_recipes = []
        elif value == "remove_recipe":
            recipe_id = request.form.get('recipe_id')
            remove_from_plan(plan, recipe_id)
        elif value == "edit_recipe":
            pass
        else:
            pass

        recipes_plan = plan.recipes  # Get only this plan's recipes

        return render_template(
            'planmaker.html',
            #lists
            recipes_search=found_recipes, 
            recipes_random=randomized_recipes, 
            recipes_plan=recipes_plan,
            #strings
            recipe_name=recipe_name,
            recipe_ingredient=recipe_ingredient,
            recipe_tag_search=recipe_tag_search,
            recipe_tag_random=recipe_tag_random,
            #objects
            user=user,
            plan=plan
        )
    else:
        recipes_plan = plan.recipes  # Get only this plan's recipes
        return render_template(
            'planmaker.html',
            #objects
            user=user,
            plan=plan,
            
            #lists
            recipes_plan=recipes_plan

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block head %} {% endblock %}
</head>
<body>
    {% block body %} {% endblock %}
</body>
</html>

templates/ingredients.html
{% extends 'base.html' %}

{% block head %} 
<title>Ingredienser</title>
<style>
    .unit-select {
        width: 180px; /* Fixed width for unit dropdown */
    }
    .action-buttons {
        display: flex;
        gap: 8px;
        flex-wrap: wrap;
    }
</style>
{% endblock %}

{% block body %} 
<div class="container mt-4">
    <div class="d-flex justify-content-center align-items-center mb-4 gap-3 flex-wrap">
        <h1 class="mb-0 text-center">Ingredienser</h1>
        <a href="{{ url_for('routes.index') }}" class="btn btn-outline-primary">🏠</a>
      </div>
    <div class="row justify-content-center">
        <div class="col-md-8">

            <!-- Flash Messages -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="mb-4">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ 'success' if category == 'success' else 'danger' }} text-center">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}

            <!-- Add Ingredient Form -->
            <div class="card mb-4">
                <div class="card-body">
                    <form action="/user/{{user.id}}/recipebank/{{recipe.id}}/ingredients" method="POST" class="row g-3">
                        <div class="col-md-4">
                            <input type="text" class="form-control" name="name" placeholder="Ingrediens" required>
                        </div>
                        <div class="col-md-3">
                            <input type="text" class="form-control" name="amount" placeholder="Mängd" required>
                        </div>
                        <div class="col-md-3">
                            <select class="form-select unit-select" name="unit" required>
                                <option value="" disabled selected>Enhet</option>
                                <option value="paket">paket</option>  
                                <option value="port">port</option>        
                                <option value="st">st</option>
                                <option value="g">g</option>
                                <option value="hg">hg</option>
                                <option value="kg">kg</option>
                                <option value="ml">ml</option>
                                <option value="cl">cl</option>
                                <option value="dl">dl</option>
                                <option value="l">l</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" name="action" value="add" class="btn btn-primary w-100">
                                Lägg till
                            </button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Ingredients Table -->
            {% if ingredients|length < 1 %}
                <div class="alert alert-info text-center">
                    Inga tillagda ingredienser
                </div>
            {% else %}
                <div class="table-responsive mb-4">
                    <table class="table table-striped table-hover">
                        <thead class="table-light">
                            <tr>
                                <th>Namn</th>
                                <th>Mängd</th>
                                <th>Åtgärder</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ingredient in ingredients %}
                                <tr>
                                    <td>{{ ingredient.name }}</td>
                                    <td>{{ ingredient.amount }}{{ ingredient.unit }}</td>
                                    <td>
                                        <div class="action-buttons">
                                            <form id="submit-form" method="POST" action="">
                                                <!-- <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}"> -->
                                                <button 
                                                    type="button" 
                                                    onclick="openModal('{{ ingredient.name }}', '{{ ingredient.amount }}', '{{ ingredient.unit }}', '{{ ingredient.id}}')" 
                                                    class="btn btn-sm btn-warning">
                                                    ✏️
                                                </button>
                                            </form>
                                            <form action="/user/{{user.id}}/recipebank/{{recipe.id}}/ingredients" method="POST" class="d-inline">
                                                <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}">
                                                <button 
                                                    type="submit" 
                                                    name="action" 
                                                    value="remove" 
                                                    class="btn btn-sm btn-danger">
                                                    🗑️
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr> 
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}

            <!-- Back Button -->
            <div class="text-center">
                <a href="{{ url_for('routes.go_back') }}" class="btn btn-secondary">
                    Tillbaka
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div id="editIngredientModal" class="modal">
    <div class="modal-content">
      <span class="close" onclick="closeModal()">&times;</span>
      <h5 class="modal-title">Ändra ingrediens</h5>
      <form method="POST" action="/user/{{user.id}}/recipebank/{{recipe.id}}/ingredients">
        <div class="mb-3">
            <label for="ingredientName" class="form-label">Namn</label>
            <input type="text" class="form-control" id="ingredientName" name="name" value="">
        </div>
        <div class="mb-3">
            <label for="ingredientAmount" class="form-label">Mängd</label>
            <input type="text" class="form-control" id="ingredientAmount" name="amount" value="">
        </div>
        <div class="mb-3">
            <label for="ingredientUnit" class="form-label">Enhet</label>
            <select class="form-select" name="unit" required>
                <option value="paket">paket</option>  
                <option value="port">port</option>   
                <option value="st">st</option>
                <option value="g">g</option>
                <option value="hg">hg</option>
                <option value="kg">kg</option>
                <option value="ml">ml</option>
                <option value="cl">cl</option>
                <option value="dl">dl</option>
                <option value="l">l</option>
            </select>
         </div>
        <input type="hidden" id="ingredientId" name="ingredient_id" value="">
        <button name="action" value="edit" type="submit" class="btn btn-sm btn-primary w-80">Ändra</button>
        <button type="button" onclick="closeModal()" class="btn btn-sm btn-secondary w-80">Avbryt</button>
      </form>
    </div>
</div>
<style>
    .modal {
      display: none;
      position: fixed;
      z-index: 10;
      left: 0; top: 0;
      width: 100%; height: 100%;
      background-color: rgba(0,0,0,0.5);
    }
  
    .modal-content {
      background-color: #fff;
      margin: 10% auto;
      padding: 20px;
      width: 300px;
      border-radius: 8px;
      position: relative;
    }
  
    .close {
      position: absolute;
      top: 5px;
      right: 10px;
      font-size: 24px;
      cursor: pointer;
    }
</style>
<script>
function openModal(name = "", amount = "", unit = "", id = "") {
    document.getElementById("editIngredientModal").style.display = "block";
    document.getElementById('ingredientName').value = name;
    document.getElementById('ingredientAmount').value = amount;
    document.getElementById('ingredientId').value = id;
    // For tag, find the select and set value
    const tagSelect = document.querySelector('#editIngredientModal select[name="unit"]');
    tagSelect.value = unit.trim().toLowerCase();
}
  
    function closeModal() {
      document.getElementById("editIngredientModal").style.display = "none";
    }
  
    // Optional: Close if clicked outside the modal
    window.onclick = function(event) {
      const modal = document.getElementById("editIngredientModal");
      if (event.target === modal) {
        modal.style.display = "none";
      }
    };
</script>

<script>
    // Initialize select elements with proper width
    document.querySelectorAll('.form-select').forEach(select => {
        select.style.width = '100%';
    });
</script>
{% endblock %}

templates/planmaker.html
{% extends 'base.html' %}

{% block head %}
<title>
  Recipe App
</title>
<style>
  /* Custom fixes for alignment */
  .equal-height-cards {
    display: flex;
    flex-direction: row;
    align-items: stretch; /* Make cards equal height */
  }
  
  .card-body {
    display: flex;
    flex-direction: column;
  }
  
  .card-content {
    flex-grow: 1; /* Push footer to bottom */
  }
  
  .table-fixed {
    table-layout: fixed;
  }
  
  .table-fixed th, .table-fixed td {
    width: 33%; /* Equal column width */
    text-align: center;
  }
</style>
{% endblock %}

{% block body %}
<div class="container mt-4">
  <div class="d-flex justify-content-center align-items-center mb-4 gap-3 flex-wrap">
    <h1 class="mb-0 text-center">Månadsplan</h1>
    <a href="{{ url_for('routes.index') }}" class="btn btn-outline-primary">🏠</a>
  </div>
  <!-- <h1 class="text-center mb-4">Månadsplan</h1> -->

  <div class="d-flex justify-content-between align-items-center mt-4 mb-2">
    <!-- Back button -->
    <a href="{{ url_for('routes.go_back')  }}" class="btn btn-secondary">Tillbaka</a>

    <!-- Flash message space (always reserved even if no message) -->
    <div class="col-md-8">
      <div class="text-center flex-grow-1 ">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ 'success' if category == 'success' else 'danger' }} text-center">
                {{ message }}
              </div>
            {% endfor %}
          {% else %}
            <!-- Invisible placeholder to reserve space -->
            <div class="invisible alert mb-0 py-2 px-3 d-inline-block">Placeholder</div>
          {% endif %}
        {% endwith %}
      </div>
    </div>

    <!-- Forward button -->
    <form method="POST">
      <a href="/user/{{user.id}}/planbank/{{plan.id}}/planmaker/ingredients" class="btn btn-primary">Fortsätt</a>
    </form>
  </div>

  <div class="row equal-height-cards">
    <!-- Search Column -->
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body text-center">
          <h2 class="card-title">Sök Recept</h2>
          <div class="card-content">
            <form method="POST" class="mb-3">
              <div class="mb-2">
                <input type="text" class="form-control text-center" name="recipe_name" value="{{ recipe_name if recipe_name else '' }}" placeholder="Receptnamn">
              </div>
              <div class="mb-2">
                <input type="text" class="form-control text-center" name="recipe_ingredient" value="{{ recipe_ingredient if recipe_ingredient else '' }}" placeholder="Ingrediens">
              </div>
              <div class="mb-2">
                <select class="form-select text-center" name="tag_search">
                  <option value="" {% if not recipe_tag_search %}selected{% endif %}>Ingen tag</option>
                  <option value="storkok" {% if recipe_tag_search == 'storkok' %}selected{% endif %}>Storkok</option>
                  <option value="vardag" {% if recipe_tag_search == 'vardag' %}selected{% endif %}>Vardag</option>
                  <option value="helg" {% if recipe_tag_search == 'helg' %}selected{% endif %}>Helg</option>
                </select>
              </div>
              <button type="submit" name="action" value="search" class="btn btn-primary w-100">Sök</button>
            </form>
            
            {% if recipes_search|length >= 1 %}
            <div class="table-responsive">
              <table class="table table-bordered">
                <thead class="table-light">
                  <tr>
                    <th class="col-10">Namn</th>
                    <th class="col-2">Åtgärd</th>
                  </tr>
                </thead>
                <tbody>
                  {% for recipe in recipes_search %}
                  <tr>
                    <td class="col-10">{{ recipe.name }}</td>
                    <td class="col-2">
                      <form action="/user/{{user.id}}/planbank/{{plan.id}}/planmaker" method="POST" class="d-inline">
                        <input type="hidden" name="recipe_id" value="{{ recipe.id }}">
                        <button type="submit" name="action" value="add" 
                          class="btn btn-success btn-sm">
                          +
                        </button>
                      </form>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            {% else %}
            <p class="text-muted mt-3">Inga recept hittade</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <!-- Random Recipe Column -->
    <div class="col-md-4 mb-4">
        <div class="card h-100">
            <div class="card-body text-center">
            <h2 class="card-title">Slumpa Recept</h2>
            <div class="card-content">
                <form method="POST" class="mb-3">
                <div class="mb-3">
                  <select class="form-select text-center" name="tag_random">
                    <option value="" {% if not recipe_tag_random %}selected{% endif %}>Ingen tag</option>
                    <option value="storkok" {% if recipe_tag_random == 'storkok' %}selected{% endif %}>Storkok</option>
                    <option value="vardag" {% if recipe_tag_random == 'vardag' %}selected{% endif %}>Vardag</option>
                    <option value="helg" {% if recipe_tag_random == 'helg' %}selected{% endif %}>Helg</option>
                  </select>
                </div>
                <button type="submit" name="action" value="random" class="btn btn-primary w-100">Slumpa</button>
                </form>
                
                {% if recipes_random|length >= 1 %}
                <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="table-light">
                    <tr>
                        <th class="col-10"> Namn</th>
                        <th class="col-2">Åtgärd</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for recipe in recipes_random %}
                    <tr>
                        <td class="col-10">{{ recipe.name }}</td>
                        <td class="col-2" >
                          <form action="/user/{{user.id}}/planbank/{{plan.id}}/planmaker" method="POST" class="d-inline">
                            <input type="hidden" name="recipe_id" value="{{ recipe.id }}">
                            <button type="submit" name="action" value="add" 
                              class="btn btn-success btn-sm">
                              +
                            </button>
                          </form>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
                {% else %}
                <p class="text-muted mt-3">Slumpa fram recept</p>
                {% endif %}
            </div>
            </div>
        </div>
        </div>

    <!-- Shopping list Column -->
    <div class="col-md-4 mb-4">
        <div class="card h-100">
          <div class="card-body text-center">
            <h2 class="card-title">Recept Inköpslista</h2>
            <div class="card-content">
              {% if recipes_plan %}
              <div class="table-responsive">
                <table class="table table-bordered">
                  <thead class="table-light">
                    <tr>
                      <th class="col-8">Namn</th>
                      <th class="col-4">Åtgärd</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for recipe in recipes_plan %}
                    <tr>
                      <td class="col-9">{{ recipe.name }}</td>
                      <td class="col-3">
                        <div class="d-flex gap-2">  <!-- Flex container with spacing -->
                          <a href="{{ url_for('routes.recipebank', user_id=user.id) }}?highlight_id={{ recipe.id }}" class="btn btn-warning btn-sm">
                            ✏️
                          </a>
                          <form method="POST">
                            <input type="hidden" name="recipe_id" value="{{ recipe.id }}">
                            <button type="submit" name="action" value="remove_recipe" class="btn btn-danger btn-sm">🗑️</button>
                          </form>
                        </div>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              {% else %}
              <p class="text-muted mt-3">Inga recept i inköpslistan ännu</p>
              {% endif %}
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
{% endblock %}